export const COLLECTION_QUERY = `
query{
  collections{
    data{
      attributes{
         name
        shortDescription
        description
        price
        category
        slug
        instock
        type
        thumbnail{
          data{
            attributes{
              formats
            }
          }
        }
        images{
          data{
            attributes{
              formats
            }
          }
        }
      }
    }
  }
}
`;
