import Head from 'next/head';
import Categories from '../sections/Categories';

import Hero from '../sections/Hero';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Hero />
        <Categories />
      </main>
    </div>
  );
}
